name: Build and Unit Test Dstv reader

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build_test_dstv_net:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            7.0.x
            8.0.x
            9.0.x
      - name: Restore dependencies
        run: dotnet restore DSTV.Net.sln
      - name: Build
        run: dotnet build DSTV.Net.sln --no-restore
      - name: Test
        run: dotnet test DSTV.Net.sln --no-build --verbosity normal
