name: Build and Unit Test Dstv reader

on:
  push:
    paths:
      - 'DSTVReader/**'
      - 'DSTVReader.Tests/**'
      - '.github/workflows/BUILD_TEST_DSTVREADER.yml'
    branches: [ develop, master ]
  pull_request:
    paths:
      - 'DSTVReader/**'
      - 'DSTVReader.Tests/**'
      - '.github/workflows/BUILD_TEST_DSTVREADER.yml'
    branches: [ develop, master ]

jobs:
  build_test_dstvreader:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore DSTVReader.sln
      - name: Build
        run: dotnet build DSTVReader.sln --no-restore
      - name: Test
        run: dotnet test DSTVReader.sln --no-build --verbosity normal

  publish_dstvreader_to_nuget:
    needs: build_test_dstvreader
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push' # Only deploy for develop branch and push event
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "todo"