name: Build and Unit Test Dstv reader

on:
  push:
    paths:
      - 'DSTV.Net/**'
      - 'DSTV.Net.Tests/**'
      - '.github/workflows/BUILD_TEST_DSTV_NET.yml'
    branches: [ develop, main ]
  pull_request:
    paths:
      - 'DSTV.Net/**'
      - 'DSTV.Net.Tests/**'
      - '.github/workflows/BUILD_TEST_DSTV_NET.yml'
    branches: [ develop, main ]

jobs:
  build_test_dstv_net:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore DSTV.Net.sln
      - name: Build
        run: dotnet build DSTV.Net.sln --no-restore
      - name: Test
        run: dotnet test DSTV.Net.sln --no-build --verbosity normal