name: Publish Packages

on:
  push:
    branches: [ main ]
    paths:
      - 'DSTV.Net/DSTV.Net.csproj'
      - 'Directory.Build.props'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            7.0.x
            8.0.x
            9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Test
        run: dotnet test
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish DTSV.Net
        run: dotnet nuget push artifacts\*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.PUBLISH_TO_NUGET_ORG}} --skip-duplicate
