name: Publish Packages

on:
  push:
    branches: [ main ]
    paths:
      - 'DSTV.Net/DSTV.Net.csproj'
      - 'Directory.Build.props'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout repository
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x
            8.0.x
            9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Test
        run: dotnet test
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish DTSV.Net
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: DSTV.Net/DSTV.Net.csproj
          NUGET_KEY: ${{secrets.PUBLISH_TO_NUGET_ORG}}
